---
- name: check for dokku installation
  stat: path=/usr/local/bin/dokku
  register: dokku_exec

# TODO: reimplement dokku's bootstrap.sh in ansible so this can be proper. it won't even be that
# hard. for now we have this ugly thing.
- name: install dokku
  shell: "wget -qO - https://raw.github.com/progrium/dokku/v0.2.3/bootstrap.sh | sudo DOKKU_TAG=v0.2.3 bash"
  async: 1200
  when: not dokku_exec.stat.exists

- name: add VHOST file
  template: src=VHOST.j2
            dest=~dokku/VHOST
            owner=dokku
            group=nogroup
            mode=0644

- name: create tls directory
  file: path=~dokku/tls
      state=directory
      owner=dokku

- name: add TLS cert
  template: src=../../../secure/wildcard.iame.li/bundle.crt
            dest=~dokku/tls/server.crt
            owner=dokku
            group=nogroup
            mode=0644

- name: add TLS key
  template: src=../../../secure/wildcard.iame.li/secret.pem
            dest=~dokku/tls/server.key
            owner=dokku
            group=nogroup
            mode=0644

- name: enable cert in nginx
  action: lineinfile dest=/etc/nginx/conf.d/dokku.conf regexp="ssl_certificate " line="ssl_certificate /home/dokku/tls/server.crt;" state=present
  notify: restart nginx

- name: enable key in nginx
  action: lineinfile dest=/etc/nginx/conf.d/dokku.conf regexp="ssl_certificate_key " line="ssl_certificate_key /home/dokku/tls/server.key;" state=present
  notify: restart nginx

- name: checkout dokku-link plugin
  git: repo=https://github.com/rlaneve/dokku-link.git
       dest=/var/lib/dokku/plugins/link
       version=94a741c6b4fda67e5b38adcd8f6d277b9a596dd2
  notify: install dokku plugins

- name: checkout dokku-redis plugin
  git: repo=https://github.com/luxifer/dokku-redis-plugin
       dest=/var/lib/dokku/plugins/redis
       version=e0611d2f0cff19034e045841595050c470370346
  notify: install dokku plugins
