---
  - name: install git
    apt: name=git state=present

  - name: install bash-completion
    apt: name=bash-completion state=present

  - name: upload .ps1
    template: src=ps1.j2 dest=~/.ps1

  - name: replace all PS1 entries in .bashrc with `cat ~/.ps1`
    replace: dest=~/.bashrc regexp='^(.*)PS1=.*' replace='PS1=`cat ~/.ps1`'
